config/routes.rb
Rails.application.routes.draw do

  get "sales/new"

  root "foods#index"
  resources :foods do
    resources :comments
  end
  
  resources :welcome
  resources :categories
  resources :cart_items
  resources :carts
  resources :administrator
  resources :about
  resources :sales
  resources :users do
     # collection do
     #  get :new_user
     # end
    resources :orders
  end

  get "display/:option" => "sales#display", as: "display"
  get "login" => "sessions#new"
  get "new_user1" => "users#new_user"
  get "user_detail" => "users#phone_num"
  get "edit_user1" => "users#edit_user", as: :edit_user1
  get "/payment/processed" => "checkout#create", as: :get_payment_completed
  get "admin" => "administrator#show", as: :dashboard
  get "admin/foods" => "administrator#food_index", as: :admin_foods
  get "admin/orders" => "administrator#order_index", as: :admin_orders
  get "admin/users" => "administrator#user_index", as: :admin_users
  get "admin/sales" => "administrator#sale_index", as: :admin_sales
  get "admin/categories" => "administrator#category_index",
      as: :admin_categories
  post "submit_user1" => "users#submit_user"
  post "login" => "sessions#create"
  post "checkout" => "checkout#show", as: :checkout
  post "carts/checkout" => "carts#checkout", as: :cart_checkout
  post "payment" => "checkout#create", as: :payment
  post "/foods/:food_id/comments(.:format)" => "comments#create",
       as: :create_food_comment
  post "/payment/processed" => "checkout#create", as: :payment_completed
  patch "order_status" => "administrator#update", as: :order_status
  patch "/foods/:food_id/edit_status" => "foods#edit_status", as: :edit_status
  delete "logout" => "sessions#destroy"
  delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  protect_from_forgery :except => [:create]
  def show
    # if logged_in?
      @current_order.ordered_items = session[:order]["items"]
    # else
    #   redirect_to login_path
    # end
  end

  def create
    # if 
    order_params = {}
    order_params[:status] = "completed"
      @current_order.update_order(session[:order], order_params)
      if @current_order.save_order(@current_user)
        session[:order] = {}
        session[:cart] = {}
        flash[:success] = "Your order has been successfully placed."
        OrderWorker.perform_async(@current_user.id, @current_order.to_json)
        redirect_to root_path
      else
        flash[:error] = "An error occured while saving your order. Please try again."
        redirect_to cart_checkout_path
      end
    end
  # end
  private

  def order_params
    { :invoice => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id]}
  end

end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/show.html.erb
<div class="full-height scroll-bar">
  <div class="pad-bottom">
    <h3>Confirm your order</h3>
    <% if @current_order.ordered_items.length == 0 %>
        <p>Your cart is still empty. What is your problem?</p>
    <% else %>
      <%= render "orders/current_order" %>
    <div>
      <%= link_to 'Back to my cart', carts_path, :class => "btn btn-success in-line left" %>
      <%= button_to 'Cash On Delivery', payment_completed_url(@current_user, payment_completed_url), :class => "btn btn-success in-line left" %>
      <%#= button_to 'Make payment', payment_completed_url(@current_user, payment_completed_url), :class => "btn btn-success in-line left" %>
    </div>
    <% end %>
  </div>


</div>