config/routes.rb
Rails.application.routes.draw do

  get "sales/new"

  root "foods#index"
  resources :foods do
    resources :comments
  end
  
  resources :welcome
  resources :categories
  resources :cart_items
  resources :carts
  resources :administrator
  resources :about
  resources :sales
  resources :users do
     # collection do
     #  get :new_user
     # end
    resources :orders
  end

  get "display/:option" => "sales#display", as: "display"
  get "login" => "sessions#new"
  get "new_user1" => "users#new_user"
  get "user_detail" => "users#phone_num"
  get "edit_user1" => "users#edit_user", as: :edit_user1
  get "/payment/processed" => "checkout#create", as: :get_payment_completed
  get "admin" => "administrator#show", as: :dashboard
  get "admin/foods" => "administrator#food_index", as: :admin_foods
  get "admin/orders" => "administrator#order_index", as: :admin_orders
  get "admin/users" => "administrator#user_index", as: :admin_users
  get "admin/sales" => "administrator#sale_index", as: :admin_sales
  get "admin/categories" => "administrator#category_index",
      as: :admin_categories
  post "submit_user1" => "users#submit_user"
  post "login" => "sessions#create"
  post "checkout" => "checkout#show", as: :checkout
  post "carts/checkout" => "carts#checkout", as: :cart_checkout
  post "payment" => "checkout#create", as: :payment
  post "/foods/:food_id/comments(.:format)" => "comments#create",
       as: :create_food_comment
  post "/payment/processed" => "checkout#create", as: :payment_completed
  patch "order_status" => "administrator#update", as: :order_status
  patch "/foods/:food_id/edit_status" => "foods#edit_status", as: :edit_status
  delete "logout" => "sessions#destroy"
  delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  before_save { self.email = email.downcase }
  validates :first_name,  presence: true, length: { maximum: 50 }
  validates :last_name,  presence: true, length: { maximum: 50 }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :address, presence: true, length: { minimum: 6 }, allow_blank: true
  # validates :email, length: { maximum: 255 },
  #                   format: { with: VALID_EMAIL_REGEX },
  #                   uniqueness: { case_sensitive: false }
  # validates :password, presence: true, length: { minimum: 6 }, allow_blank: true

  has_many :orders, dependent: :destroy

  # has_attached_file :avatar, styles: { :original => "150x150", :small => "64x64", :med => "200x200", :large => "300x300" }, :default_url => "yuna.jpg"
  # validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # validates_attachment_size :avatar, :in => 0.megabytes..1.megabytes

  has_many :comments, dependent: :destroy

 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def phone_num
    @user = User.new
  end

  def new_user
    @user = User.new
  end

  def submit_user
    # User.where(phone_number: params[:user][:phone_number]).first
    @users = User.where(phone_number: params[:user][:phone_number])
    # @users = User.find_all_by_phone_number(params[:user][:phone_number])
    if @users.present?
      # @user = @users.first
      # redirect_to edit_user1_path(@user)
      redirect_to edit_user1_path(id: @users.first.id)
    else
      redirect_to new_user1_path
    end
  end

  def edit_user
    @user = User.find_by_id(params[:id])    
  end
  # def create
  #   @user = User.new(user_params)
  #   @image = user_params[:avatar]
  #   uploader_checker(@image) if @image
  #   @user[:avatar_file_name] = @avatar_url
  #   if @user.save
  #     log_in @user
  #     flash[:success] = "Welcome #{user_params[:first_name]} to dinner dash!"
  #     MailerWorker.perform_async(@user.id)
  #     redirect_to root_path
  #   else
  #     flash[:error] = "One or more required fields are missing"
  #     render "new"
  #   end
  # end


  def create
    @current_order.ordered_items = session[:order]["items"]
    @user = User.new(user_params)
    @image = user_params[:avatar]
    uploader_checker(@image) if @image
    @user[:avatar_file_name] = @avatar_url
    if @user.save
      log_in @user
      flash[:success] = "Welcome #{user_params[:first_name]} to dinner dash!"
      MailerWorker.perform_async(@user.id)
      redirect_to root_path
    else
      flash[:error] = "One or more required fields are missing"
      render "new_user"
    end
  end
  def show
    @user = User.find_by(id: params[:id])
    args = args_params || {}
    if @user
      if !args.nil?
        @orders = @user.orders
        @title = args[:title] || "Profile"
      else
        @orders = @user.orders.order(created_at: :desc).limit(3)
        @title = "Recent Orders"
      end
    else
      flash[:message] = "We're sorry we couldn't find any information for this user."
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes!(user_params)
      log_in @user
      flash[:success] = "Thanks For Selecting Us"
      redirect_to root_path
    else
      redirect_to edit_user1_path(id: @user.id)
    end
  end

  def upload_image(text)
    @upload = {}
    @upload[:avatar] = Cloudinary::Uploader.upload(text)
    @avatar_url = @upload[:avatar]["url"]
  end

  def destroy
    user = User.find(params[:id])
    if user
      user.destroy
      flash[:success] = "#{user.first_name} has been deleted."
      redirect_to dashboard_path
    else
      flash[:error] = "An error occured. Try deleting #{@user.first_name} again."
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :address, :dob, :land_mark)
  end

  def args_params
    args = params.require(:args).permit(:show_all, :title) if params.has_key? "args"
  end

  def uploader_checker(image)
    if image.size < 1.megabytes
      upload_image(image)
    else
      flash[:warning] = "file size must be between 0 and 1 megabytes"
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
<h4>Edit Profile</h4>
<%= form_for @user, :html => { :multipart => true, :class => "col s12" } do |f| %>
  <div class="row">
    <div class="input-field col s6">
      <%=f.text_field :first_name, :class => "validate" %>
      <%= f.label :first_name %>
      <div class = "error"><%= @user.errors.messages[:first_name][0] %></div>
    </div>
    <div class="input-field col s6">
      <%=f.text_field :last_name, :class => "validate" %>
      <%= f.label :last_name %>
      <div class = "error"><%= @user.errors.messages[:last_name][0] %></div>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%=f.email_field :email, :class => "validate" %>
      <%= f.label :email, :class => "active", "data-error" => "#{@user.errors.messages['email']}" %>
      <div class = "error"><%= @user.errors.messages[:email][0] %></div>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%=f.password_field :password, :class => "validate" %>
      <%= f.label :password %>
      <div class = "error"><%= @user.errors.messages[:password][0] %></div>
    </div>
  </div>
  <div class="row">
  <div class="input-field col s12">
      <%=f.password_field :password_confirmation, :class => "validate" %>
      <%= f.label :password_confirmation %>
      <div class = "error"><%= @user.errors.messages[:password_confirmation][0] %></div>
  </div>
  <div class="row">
    <div class="col s12">
      <!--<%= link_to image_tag(@user.avatar.url(:med)), @user.avatar.url%>-->
      <%= f.file_field :avatar %>
    </div>
  </div>
<%= f.submit "Save Changes", :class => "btn waves-effect waves-light" %>
<% end %>

app/views/users/edit_user.html.erb
<div class="row container full-height scroll-bar">
<h4>Fill the details.</h4>
  <%= form_for @user, :html => { :multipart => true, :class => "col s12" } do |f| %>
    <div class="row">
      <div class="input-field col s6">
        <%=f.text_field :first_name, :class => "validate" %>
        <%= f.label :first_name %>
        <div class = "error"><%= @user.errors.messages[:first_name][0] %></div>
      </div>
      <div class="input-field col s6">
        <%=f.text_field :last_name, :class => "validate" %>
        <%= f.label :last_name %>
        <div class = "error"><%= @user.errors.messages[:last_name][0] %></div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%=f.email_field :email, :class => "validate" %>
        <%= f.label :email, :class => "active", "data-error" => "#{@user.errors.messages['email']}" %>
        <div class = "error"><%= @user.errors.messages[:email][0] %></div>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= "DOB" %>
        <%= f.date_field :dob, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), :class => "active", "data-error" => "#{@user.errors.messages['dob']}" %>
        <div class = "error"><%= @user.errors.messages[:first_name][0] %></div>
      </div>
      <div class="input-field col s6">
        <%= f.label :phone_number %>
        <%=f.text_field :phone_number, :class => "validate" %>
        <div class = "error"><%= @user.errors.messages[:phone_number][0] %></div>
      </div>
    </div>


    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :land_mark, :class => "validate" %>
        <%= f.label :land_mark, :class => "active", "data-error" => "#{@user.errors.messages['land_mark']}" %>
        <div class = "error"><%= @user.errors.messages[:land_mark][0] %></div>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :address, :class => "validate" %>
        <%= f.label :address %>
        <!-- <div class = "error"><%#= @user.errors.messages[:address][0] %></div> -->
      </div>
    </div>
    
  <%= f.submit "Proceed to Checkout", :class => "btn" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="row container full-height scroll-bar">
<h4>SignUp</h4>
  <!-- <% if !@user.errors.messages.empty? %> -->
    <!-- <% @user.errors.messages.each do |error, message| %>
      <script>Materialize.toast("<%= error %> <%= message.to_s %>", 5000, 'rounded', 'success')();</script>
    <% end %>
  <% end %> -->
  <%= form_for @user, :html => { :multipart => true, :class => "col s12" } do |f| %>
    <div class="row">
      <div class="input-field col s6">
        <%=f.text_field :first_name, :class => "validate" %>
        <%= f.label :first_name %>
        <div class = "error"><%= @user.errors.messages[:first_name][0] %></div>
      </div>
      <div class="input-field col s6">
        <%=f.text_field :last_name, :class => "validate" %>
        <%= f.label :last_name %>
        <div class = "error"><%= @user.errors.messages[:last_name][0] %></div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%=f.email_field :email, :class => "validate" %>
        <%= f.label :email, :class => "active", "data-error" => "#{@user.errors.messages['email']}" %>
        <div class = "error"><%= @user.errors.messages[:email][0] %></div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :phone_number, :class => "validate" %>
        <%= f.label :phone_number %>
        <!-- <div class = "error"><%#= @user.errors.messages[:password][0] %></div> -->
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :address, :class => "validate" %>
        <%= f.label :address %>
        <!-- <div class = "error"><%#= @user.errors.messages[:password][0] %></div> -->
      </div>
    </div>
    
    <div class="row">
      <div class="input-field col s12">
        <%=f.password_field :password, :class => "validate" %>
        <%= f.label :password %>
        <div class = "error"><%= @user.errors.messages[:password][0] %></div>
      </div>
    </div>
    
    <div class="row">
    <div class="input-field col s12">
        <%=f.password_field :password_confirmation, :class => "validate" %>
        <%= f.label :password_confirmation %>
        <div class = "error"><%= @user.errors.messages[:password_confirmation][0] %></div>
    </div>
    <div class="row">
      <div class="col s12">
        <!--<%= link_to image_tag(@user.avatar.url(:med)), @user.avatar.url%>-->
        <%= f.file_field :avatar %>
      </div>
    </div>
  <%= f.submit "Sign up", :class => "btn" %>
  <% end %>
</div>

app/views/users/new_user.html.erb
<div class="row container full-height scroll-bar">
<h4>Fill the details.</h4>
  <%= form_for @user, :html => { :multipart => true, :class => "col s12" } do |f| %>
    <div class="row">
      <div class="input-field col s6">
        <%=f.text_field :first_name, :class => "validate" %>
        <%= f.label :first_name %>
        <div class = "error"><%= @user.errors.messages[:first_name][0] %></div>
      </div>
      <div class="input-field col s6">
        <%=f.text_field :last_name, :class => "validate" %>
        <%= f.label :last_name %>
        <div class = "error"><%= @user.errors.messages[:last_name][0] %></div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%=f.email_field :email, :class => "validate" %>
        <%= f.label :email, :class => "active", "data-error" => "#{@user.errors.messages['email']}" %>
        <div class = "error"><%= @user.errors.messages[:email][0] %></div>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= "DOB" %>
        <%= f.date_field :dob, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), :class => "active", "data-error" => "#{@user.errors.messages['dob']}" %>
        <div class = "error"><%= @user.errors.messages[:first_name][0] %></div>
      </div>
      <div class="input-field col s6">
        <%=f.text_field :phone_number, :class => "validate" %>
        <%= f.label :phone_number %>
        <div class = "error"><%= @user.errors.messages[:phone_number][0] %></div>
      </div>
    </div>


    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :land_mark, :class => "validate" %>
        <%= f.label :land_mark, :class => "active", "data-error" => "#{@user.errors.messages['land_mark']}" %>
        <div class = "error"><%= @user.errors.messages[:land_mark][0] %></div>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :address, :class => "validate" %>
        <%= f.label :address %>
        <!-- <div class = "error"><%#= @user.errors.messages[:address][0] %></div> -->
      </div>
    </div>
    
  <%= f.submit "Proceed to Checkout", :class => "btn" %>
  <% end %>
</div>

app/views/users/phone_num.html.erb
<div class="row container full-height scroll-bar">
<h4>Fill the details.</h4>
  <%= form_for @user, :html => { :multipart => true, :class => "col s12" }, :url =>  url_for(:action => "submit_user") do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :phone_number, :class => "validate" %>
        <%= f.label :phone_number %>
      </div>
    </div>
    
  <%= f.submit "Continue", :class => "btn" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row full-height">
  <% if @user %>
    <div class="col s4 full-height scroll-bar profile_left_tab">
      <div class="card medium">
        <div class="card-image">
          <%= image_tag @user.avatar.url%>
        </div>
        <div class="card-content">
          <p>Name: <%= @user.first_name %> <%= @user.last_name %></p>
          <p>Email: <%= @user.email %></p>
        </div>
        <div class="card-action">
          <%= link_to "Edit Profile", edit_user_path(@user.id)  %>
        <!-- </div> -->
        <!-- <div class="card-action"> -->
        <%= link_to "View Orders", :args => { :show_all => true , :title => "All Orders"} %>
        </div>
      </div>
    </div>

    <div class="col s8">
      <h4 class="order_header"><%= @title %></h4>
        <%= render "layouts/orders_page" %>
    </div>
  <% else %>
    <div class="container">There is no user to display</div>
  <% end %>
</div>