config/routes.rb
Rails.application.routes.draw do

  get "sales/new"

  root "foods#index"
  resources :foods do
    resources :comments
  end
  
  resources :welcome
  resources :categories
  resources :cart_items
  resources :carts
  resources :administrator
  resources :about
  resources :sales
  resources :users do
     # collection do
     #  get :new_user
     # end
    resources :orders
  end

  get "display/:option" => "sales#display", as: "display"
  get "login" => "sessions#new"
  get "new_user1" => "users#new_user"
  get "user_detail" => "users#phone_num"
  get "edit_user1" => "users#edit_user", as: :edit_user1
  get "/payment/processed" => "checkout#create", as: :get_payment_completed
  get "admin" => "administrator#show", as: :dashboard
  get "admin/foods" => "administrator#food_index", as: :admin_foods
  get "admin/orders" => "administrator#order_index", as: :admin_orders
  get "admin/users" => "administrator#user_index", as: :admin_users
  get "admin/sales" => "administrator#sale_index", as: :admin_sales
  get "admin/categories" => "administrator#category_index",
      as: :admin_categories
  post "submit_user1" => "users#submit_user"
  post "login" => "sessions#create"
  post "checkout" => "checkout#show", as: :checkout
  post "carts/checkout" => "carts#checkout", as: :cart_checkout
  post "payment" => "checkout#create", as: :payment
  post "/foods/:food_id/comments(.:format)" => "comments#create",
       as: :create_food_comment
  post "/payment/processed" => "checkout#create", as: :payment_completed
  patch "order_status" => "administrator#update", as: :order_status
  patch "/foods/:food_id/edit_status" => "foods#edit_status", as: :edit_status
  delete "logout" => "sessions#destroy"
  delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete

end

app/models/food.rb
class Food < ActiveRecord::Base
  after_create :create_sale
  belongs_to :category
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :comments
  serialize :sales

  has_attached_file :food_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "nigerian-jollof-rice.jpg"
  validates_attachment_content_type :food_image, :content_type => /\Aimage\/.*\Z/

  def create_sale
    self.sales = Hash.new
    sales[:price] = 0.00
    sales[:percentage] = 0
    sales[:status] = false
    save
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :check_if_admin,
                only: [:create, :destroy, :update, :edit_status]

  def index
    if current_user.present?
      @foods = Food.all.order(created_at: :asc)
    else
      redirect_to user_detail_path
    end
  end

  def new
    @food = Food.new
  end

  def edit
    @food = Food.find(params[:id])
    render template: "foods/new"
  end

  def create
    @food = {}
    if upload_image
      @food = Food.create(food_params)
      flash[:success] = "#{@food.name} has been added successfully."
      redirect_to dashboard_path
    else
      flash[:error] = "An error occured. Try adding #{@food.name} again."
    end
  end

  def show
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    upload_image if food_params[:food_image]
    if @food
      save_food
    else
      flash[:error] = "An error occured. Try adding #{@food.name} again."
    end
  end

  def destroy
    food = Food.find(params[:id])
    if food
      food.destroy
      flash[:success] = "#{food.name} has been deleted."
      redirect_to dashboard_path
    else
      flash[:error] = "An error occured. Try deleting #{@food.name} again."
    end
  end

  def edit_status
    food = Food.find(food_params[:id].to_i)
    unless food.nil?
      status = food_params[:status] == "true" ? "available" : "not available"
      food.status = status
      food.save
      render json: food
    end
  end

  private

  def food_params
    params.require(:food).permit(:id, :name, :description, :price,
                                 :category_id, :food_image, :status,:prep_time,
                                 sales: [:percentage, :price,
                                         :status, :js])
  end

  def upload_image
    image = food_params[:food_image]
    @food_image_url = false
    if image && image.size < 1.megabytes
      @upload = {}
      @upload[:food_image] = Cloudinary::Uploader.upload(image)
      @food_image_url = @upload[:food_image]["url"]
      @food[:food_image_file_name] = @food_image_url
    else
      flash[:warning] = "file size must be between 0 and 1 megabytes"
    end
    @food_image_url
  end

  def save_food
    @food[:food_image_file_name] = @food_image_url
    if food_params[:sales][:js]
      food = food_params[:sales]
      food_status = (food["status"] == "true") ? true : false
      @food.update(sales: { price: food["price"].to_f,
                            percentage: food["percentage"].to_f,
                            status: food_status })
      render json: { success: true }
    else
      @food.update(food_params)
      flash[:success] = "#{@food.name} has been updated successfully."
      redirect_to dashboard_path
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<div class="row full-height">
 <%=render 'layouts/category' %>
 <div class="col s9 full-height scroll-bar">
   <div class="panel header-panel flow-text z-depth-3"><%= (!@category.nil?) ? @category.title : "All cuisines"  %></div>
  <div class="row"> <% @foods = (!@category.nil?) ? @category.foods : @foods  %>
  <% @foods.each do |food| %>
      <div class="col s12 m6 l4">
        <div class="card">
          <div class="card-image">
          <% if food.sales[:status] %>
            <span class="price-tag"><s> <%= "Rs " %> <%= food.price%></s></span>
            <span class="price-tag">Sales! Rs <%= food.sales[:price]%></span>
          <% else %>
            <span class="price-tag"><%= " Rs " %><%= food.price%></span>
          <% end %>
            <span class="activator"><i class="material-icons right">more_vert</i></span>
            <%= link_to(food) do %>
              <%= image_tag((food.food_image.url || "nigerian-jollof-rice.jpg"), :width => "100%", :height => "auto", :style => "max-width:100%", :class => "image-thumb", :alt => "food") %>
              <span class="card-title"><%= food.name %></span>
            <% end %>
          </div>
          <div class="card-action">
            <div class="right"><i class="material-icons left no-right-margin">shopping_cart</i><%= link_to "
						 #{this_food_in_cart(food)}", carts_path, class: "cart left no_left_pad no-right-margin", id: "cart" %></div>
            <% if food.status == "available" %>
              <%= button_to "Add to cart", cart_items_path(food_id: food.id) %>
            <% else %>
              <p>Out of stock</p>
            <% end %>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= food.name%><i class="material-icons right">close</i></span>
            <% if food.sales[:status] %>
            <p><s><%= food.price%></s></p>
            <p>New Price: <%= food.sales[:price]%></p>
            <% else %>
            <p><%= food.price%></p>
            <% end %>
            <p><%= food.description%></p>
          </div>
        </div>
      </div>

  <% end %>
  </div>
 </div>
</div>

app/views/foods/new.html.erb
<div class="row container full-height scroll-bar">
<h4>Create new food</h4>
  <%= form_for @food, :html => { :multipart => true, :class => "col s12" } do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :name, :class => "validate" %>
        <%= f.label :name %>
        <div class = "error"><%= @food.errors.messages[:name][0] %></div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :description, :class => "validate" %>
        <%= f.label :description, :class => "active", "data-error" => "#{@food.errors.messages['description']}" %>
        <div class = "error"><%= @food.errors.messages[:description][0] %></div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%=f.text_field :price, :class => "validate" %>
        <%= f.label :price %>
        <div class = "error"><%= @food.errors.messages[:price][0] %></div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s6">
        <%=f.text_field :prep_time, :class => "validate" %>
        <%= f.label "Prep time in mins" %>
        <div class = "error"><%= @food.errors.messages[:prep_time][0] %></div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
          <%= f.collection_select(:category_id, Category.all, :id, :title, {}, { :class => "select_box", :style => "display:block;" }) %>
          <div class = "error"><%= @food.errors.messages[:category_id][0] %></div>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <%= f.file_field :food_image %>
      </div>
      <div class="food_upload_progress_bar">
        <div class="determinate" style="width: 70%"></div>
      </div>
    </div>
  <%= f.submit "Add food", :class => "btn waves-effect waves-light" %>
  <% end %>
</div>

app/views/foods/show.html.erb
<div class="full-height scroll-bar">
  <div class="row">
    <div class="col s12 m6 l6 flow-text">
      <h3><%= @food.name%></h3>
      <p><%= @food.description %></p>
      <p><%= @food.price %></p>
    </div>

    <div class="container col s12 m6 l6">
      <%= image_tag @food.food_image.url %>
    </div>
  </div>

  <h5>Comments</h5>
  <div class="comments">
    <% @food.comments.each do |comment| %>
      <div class="divider"></div>
      <div class="section">
        <h6><%= "#{comment.user.first_name} #{comment.user.last_name} says" %></h6>
        <p><%= comment.comment %></p>
      </div>
    <% end %>
    <% if logged_in? %>
      <h5>Add a comments</h5>
      <%= form_for "comment", :url => {:controller => 'comments', :action => 'create', :food_id => @food.id, :user_id => @current_user.id, method: :post} do |f| %>
        <div class="divider"></div>
        <div class="section">
          <h6><%= f.text_field :comment, :id => "comment" %></h6>
      <% end %>
          <p><%= button_to "Add comment", create_food_comment_path(@food), "data-foodid" => "#{@food.id}", "data-userid" => "#{@current_user.id}", :id => "add_comment" %></p>
        </div>
    <% end %>
  </div>
</div>